import type { Tournament } from './types'

/** Données de démo — à remplacer par Supabase (kora_tournaments). */
export const MOCK_TOURNAMENTS: Tournament[] = [
  {
    id: 't-weekend-kora',
    name: 'Kora du Week-end',
    status: 'open',
    format: 'single_elim',
    entryFeeFcfa: 500,
    prizePoolFcfa: 25_000,
    prizes: [
      { rank: 1, label: 'Champion', amountFcfa: 15_000 },
      { rank: 2, label: 'Finaliste', amountFcfa: 7_000 },
      { rank: 3, label: 'Demi', amountFcfa: 3_000 },
    ],
    maxPlayers: 16,
    registeredCount: 9,
    startsAt: new Date(Date.now() + 1000 * 60 * 60 * 6).toISOString(),
    tagline: 'Élimination directe · 16 places · mise 500',
    rulesPreset: 'standard',
  },
  {
    id: 't-free-friday',
    name: 'Vendredi Gratuit',
    status: 'open',
    format: 'rounds_race',
    entryFeeFcfa: 0,
    prizePoolFcfa: 5_000,
    prizes: [
      { rank: 1, label: '1er', amountFcfa: 3_000 },
      { rank: 2, label: '2e', amountFcfa: 1_500 },
      { rank: 3, label: '3e', amountFcfa: 500 },
    ],
    maxPlayers: 32,
    registeredCount: 18,
    startsAt: new Date(Date.now() + 1000 * 60 * 60 * 24).toISOString(),
    tagline: 'Sans buy-in · course aux rounds · sponsored',
    rulesPreset: 'training',
  },
  {
    id: 't-night-live',
    name: 'Table de Minuit',
    status: 'live',
    format: 'swiss',
    entryFeeFcfa: 1_000,
    prizePoolFcfa: 40_000,
    prizes: [
      { rank: 1, label: '1er', amountFcfa: 25_000 },
      { rank: 2, label: '2e', amountFcfa: 10_000 },
      { rank: 3, label: '3e', amountFcfa: 5_000 },
    ],
    maxPlayers: 12,
    registeredCount: 12,
    startsAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    tagline: 'En cours · format suisse · buy-in 1 000',
    rulesPreset: 'high_stakes',
  },
  {
    id: 't-past-cup',
    name: 'Coupe Paparas #12',
    status: 'completed',
    format: 'single_elim',
    entryFeeFcfa: 500,
    prizePoolFcfa: 20_000,
    prizes: [{ rank: 1, label: 'Vainqueur', amountFcfa: 20_000 }],
    maxPlayers: 8,
    registeredCount: 8,
    startsAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    tagline: 'Terminé · archives',
    rulesPreset: 'standard',
  },
]
